### PR TITLE
Adding Collections Category

### PR DESCRIPTION
**Pull request by mehdihadeli**

### CODE REVIEW

**Comment by linkdotnet** [comment]
Thank you very much @mehdihadeli . 

You kept me think to merge your new "collection" tab with the current "IEnumerable" tab. I like "collection" more.

**Comment by mehdihadeli** [comment]
Thanks @linkdotnet,
We could add very things in this section

**Comment by linkdotnet** [comment]
If we have a lot in one specific topic like `IEnumerable<T>` or so we can just create a sub-page.
Thanks again for the effort. Much appreciated.

**Comment by mehdihadeli** [comment]
Yes, we could have a collection folder and inner this folder two files: `collection.md` for general things and `enumerable.md` for enumerable specific things

**Pull request merged**
